# Generated by Django 3.0.4 on 2020-05-26 10:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='https://cdn.wzz.ink/avatar/defaultAvatar.png', max_length=512, upload_to=''),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='birthday',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 5, 26, 10, 29, 23, 523909)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='registerinfo',
            field=models.CharField(default='000', max_length=2),
        ),
    ]
