# Generated by Django 3.0.4 on 2020-06-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jitang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addtime', models.DateTimeField(auto_now_add=True)),
                ('jitang', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '心灵鸡汤',
                'verbose_name_plural': '心灵鸡汤',
                'db_table': 'Jitang',
            },
        ),
    ]
