# Generated by Django 3.0.4 on 2020-05-26 21:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200526_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='birthday',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 5, 26, 21, 23, 29, 48148)),
        ),
    ]
