# Generated by Django 3.0.4 on 2020-05-28 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200526_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userType',
            field=models.CharField(default='普通用户', max_length=25),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='birthday',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 5, 28, 16, 25, 50, 967559)),
        ),
    ]
