# Generated by Django 3.0.3 on 2020-04-26 20:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thought',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('type_raw', models.CharField(max_length=4)),
                ('type_ai', models.CharField(blank=True, max_length=4, null=True)),
                ('type_human', models.CharField(blank=True, max_length=4, null=True)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_time', models.DateTimeField(blank=True, null=True)),
                ('views', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'compayu_thought',
            },
        ),
    ]
