# Generated by Django 3.0.6 on 2020-05-29 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compayu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editor',
            options={'verbose_name': '富文本编辑器', 'verbose_name_plural': '富文本编辑器'},
        ),
        migrations.AlterModelTable(
            name='editor',
            table='Editor',
        ),
    ]
