# Generated by Django 3.0.3 on 2020-04-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compayu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thought',
            name='type_ai',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='thought',
            name='type_human',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='thought',
            name='type_raw',
            field=models.CharField(max_length=20),
        ),
    ]
