# Generated by Django 3.0.4 on 2020-05-31 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compayu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thought',
            name='viewtimes',
            field=models.IntegerField(default=0, max_length=255),
        ),
    ]
