# Generated by Django 3.0.4 on 2020-06-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compayu', '0002_thought_viewtimes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thought',
            name='viewtimes',
            field=models.IntegerField(default=0),
        ),
    ]
