# Generated by Django 3.0.4 on 2020-06-01 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compayu', '0003_auto_20200601_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thought',
            name='viewtimes',
        ),
    ]
